import type { Config } from "tailwindcss";

// Theme copied verbatim from the original landing page (index.html) so every
// class renders identically to the approved design.
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#334955",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-surface": "#171d1e",
        "surface-container-highest": "#dee3e4",
        "on-tertiary-fixed-variant": "#334a56",
        "primary-container": "#006680",
        "tertiary-fixed": "#cee6f5",
        "primary-fixed-dim": "#87d1ee",
        "primary-fixed": "#b9eaff",
        "tertiary-fixed-dim": "#b2cad9",
        "surface-container": "#eaeff0",
        "secondary-container": "#fd6604",
        "error-container": "#ffdad6",
        "outline-variant": "#bfc8cd",
        "inverse-on-surface": "#edf2f3",
        "on-secondary-fixed": "#360f00",
        "surface-variant": "#dee3e4",
        "on-surface-variant": "#3f484c",
        surface: "#f5fafb",
        "secondary-fixed": "#ffdbcd",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#004d62",
        "surface-dim": "#d6dbdc",
        primary: "#004d61",
        background: "#f5fafb",
        "surface-container-high": "#e4e9ea",
        "surface-container-low": "#eff4f5",
        "on-tertiary-fixed": "#051e29",
        "on-error": "#ffffff",
        secondary: "#a33e00",
        "inverse-primary": "#87d1ee",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001f29",
        "secondary-fixed-dim": "#ffb596",
        "on-tertiary-container": "#c3dbea",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#541d00",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#026781",
        outline: "#6f787d",
        "on-background": "#171d1e",
        "on-secondary-fixed-variant": "#7c2e00",
        "tertiary-container": "#4a616d",
        "on-primary-container": "#99e1ff",
        "inverse-surface": "#2c3132",
        "surface-bright": "#f5fafb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
